<a href="https://colab.research.google.com/github/NachuanLi/demo/blob/master/ECE539HW3PB2NachuanLi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
y=np.array([[1.8],[3.9],[5.2],[6.5]])
x=np.array([[1,1],[2,1],[3,1],[4,1]])

In [5]:
DC=np.linalg.svd(x)
DC

(array([[-0.21952944, -0.80734554, -0.40008743, -0.37407225],
        [-0.38334247, -0.3912142 ,  0.25463292,  0.79697056],
        [-0.5471555 ,  0.02491713,  0.69099646, -0.47172438],
        [-0.71096853,  0.44104847, -0.54554195,  0.04882607]]),
 array([5.77937881, 0.77380911]),
 array([[-0.94673755, -0.32200622],
        [ 0.32200622, -0.94673755]]))

In [6]:
xt=np.transpose(x)
xtx = np.matmul(xt,x) 
xtx

array([[30, 10],
       [10,  4]])

In [7]:
xtx_inv=np.linalg.inv(xtx)
xtx_inv

array([[ 0.2, -0.5],
       [-0.5,  1.5]])

In [8]:
#parta
#compute the pseudo inverse of X
x_psu=np.matmul(xtx_inv,xt)
x_psu

array([[-0.3, -0.1,  0.1,  0.3],
       [ 1. ,  0.5,  0. , -0.5]])

In [9]:
A=np.matmul(x_psu, x)
B=np.matmul(x, x_psu)

In [11]:
# part b --A
A

array([[1.00000000e+00, 1.66533454e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [12]:
# part b --B
B

array([[ 0.7,  0.4,  0.1, -0.2],
       [ 0.4,  0.3,  0.2,  0.1],
       [ 0.1,  0.2,  0.3,  0.4],
       [-0.2,  0.1,  0.4,  0.7]])

In [15]:
# part c
w=np.matmul(x_psu,y )
w

array([[1.54],
       [0.5 ]])

In [18]:
#w*1
w[0][0]

1.54

In [19]:
#w*0
w[1][0]

0.49999999999999956

In [24]:
# f value
e=np.matmul(x, w)-y
f=np.matmul(np.transpose(e),e)
f[0][0]


0.19200000000000017