<a href="https://colab.research.google.com/github/NachuanLi/demo/blob/master/ECE539HW3PB1NachuanLi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import numpy as np
import pandas as pd
import math

In [32]:
data1=pd.read_csv("iris.csv", header=None)
data=data1[[2,3,4]]
data

2    3  4
0    1.4  0.2  1
1    1.4  0.2  1
2    1.3  0.2  1
3    1.5  0.2  1
4    1.4  0.2  1
..   ...  ... ..
145  5.2  2.3  3
146  5.0  1.9  3
147  5.2  2.0  3
148  5.4  2.3  3
149  5.1  1.8  3

[150 rows x 3 columns]

In [33]:
train_data=data[0:151:2]
test_data=data[1:150:2]

#assign categories
train1=train_data[train_data[4]==1]
train2=train_data[train_data[4]==2]
train3=train_data[train_data[4]==3]

test1=test_data[test_data[4]==1]
test2=test_data[test_data[4]==2]
test3=test_data[test_data[4]==3]

In [92]:
# mean class 1 trait 2
mu12=train1[[2]].mean()
mu12

2    1.456
dtype: float64

In [93]:
# mean class 1 trait 3
mu13=train1[[3]].mean()
mu13

3    0.224
dtype: float64

In [81]:
#covariance of class 1 for trait 2 and 3
lst12=np.transpose(train1[[2]].values)[0]
lst13=np.transpose(train1[[3]].values)[0]
cov1=np.cov(np.array([lst12,lst13]),bias=True)
cov1

array([[0.040864, 0.003456],
       [0.003456, 0.006624]])

In [90]:
# mean class 2 trait 2
mu22=train2[[2]].mean()
mu22

2    4.308
dtype: float64

In [91]:
# mean class 3 trait 3
mu23=train2[[3]].mean()
mu23

3    1.352
dtype: float64

In [80]:
#covariance of class 2 for trait 2 and 3
lst22=np.transpose(train2[[2]].values)[0]
lst23=np.transpose(train2[[3]].values)[0]
cov2=np.cov(np.array([lst22,lst23]),bias=True)
cov2

array([[0.220736, 0.069584],
       [0.069584, 0.036096]])

In [94]:
# mean class 3 trait 2
mu32=train3[[2]].mean()
mu32

2    5.564
dtype: float64

In [102]:
# mean class 3 trait 3
mu33=train3[[3]].mean()
mu33

3    2.076
dtype: float64

In [79]:
#covariance of class 3 for trait 2 and 3
lst32=np.transpose(train3[[2]].values)[0]
lst33=np.transpose(train3[[3]].values)[0]
cov3=np.cov(np.array([lst32,lst33]),bias=True)
cov3

array([[0.285504, 0.049536],
       [0.049536, 0.074624]])

In [89]:
# partb
# daterminat of cov matrix of class 1
det1=np.linalg.det(cov1)
det1

0.0002587391999999999

In [88]:
# daterminat of cov matrix of class 2
det2=np.linalg.det(cov2)
det2

0.0031257536000000035

In [87]:
# daterminat of cov matrix of class 3
det3=np.linalg.det(cov3)
det3

0.01885163520000001

In [108]:
# part c
x=[[4.4],[1.4]]
det={1:det1, 2:det2, 3:det3}
cov={1:cov1, 2:cov2, 3:cov3}
mu={1:{2:(mu12.values)[0], 3:(mu13.values)[0]}, 2: {2:(mu22.values)[0], 3:(mu23.values)[0]}, 3:{2:(mu32.values)[0], 3:(mu33.values)[0]}}

def Lk(k=None, x=None):
  #print(x)
  #print([[mu[k][2]],[mu[k][3]]])
  x_uk=np.subtract(x,[[mu[k][2]],[mu[k][3]]])
  x_uk_t=np.transpose(x_uk)
  covk_1=np.linalg.inv(cov[k])
  a=np.matmul(x_uk_t, covk_1)
  b=np.matmul(a, x_uk)
  return (1/2/math.pi/det[k])*math.exp(-0.5*b[0])

def lk(k=None, x=None):
  return np.log(Lk(k=k, x=x))


In [107]:
# L1
Lk(k=1, x=x)

1.8229614381411095e-73

In [109]:
# l1
lk(k=1, x=x)

-167.48824944605957

In [110]:
# L2
Lk(k=2, x=x)

49.31785960259407

In [111]:
# l2
lk(k=2, x=x)

3.8982862791912787

In [112]:
# L3
Lk(k=3, x=x)

0.14353587937046494

In [113]:
# l3
lk(k=3, x=x)

-1.9411702445786647

In [189]:
def classify(test=None):
  classify={1:0, 2:0, 3:0}
  for row in test[[2,3]].iterrows():
    e=[lk(k=1, x=[[row[1].values[0]], [row[1].values[1]]]), lk(k=2, x=[[row[1].values[0]], [row[1].values[1]]]), lk(k=3, x=[[row[1].values[0]], [row[1].values[1]]])] 
    #print(e)
    classify[np.argmax(e)+1]+=1
  return classify

classify(test=test3)


{1: 0, 2: 2, 3: 23}

In [190]:
# classification of test class1
classify(test=test1)

{1: 25, 2: 0, 3: 0}

In [191]:
# classification of test class1
classify(test=test2)

{1: 0, 2: 25, 3: 0}

In [192]:
classify(test=test3)

{1: 0, 2: 2, 3: 23}