If using google colab, you need to upload the .mat file before you can use it. This cell won't need to run if you are running jupyter locally. You only need to run it if the ex_conv2data.mat file isn't located where jupyter can find it. 

In [ ]:
from google.colab import files

uploaded = files.upload()

This sell sets up a flag called newdata. When the button is checked, Newdata will return true and we will randomly generate new data. When the button is not checked, we will instead use the .mat file. 

In [9]:
import ipywidgets as widgets

# Widget allows us to toggle the randomized data flag on and off. 
newdata = widgets.ToggleButton(
    value=False,
    description='Randomize Data',
    disabled=False,
    button_style='', # 'success', 'info', 'warning', 'danger' or ''
    tooltip='Description',
    icon='check' # (FontAwesome names without the `fa-` prefix)
)
newdata


ToggleButton(value=False, description='Randomize Data', icon='check', tooltip='Description')

In [21]:
import numpy as np
from scipy.signal import convolve2d
from scipy.io import loadmat
from google.colab import files


F = 3                 # The size of our filter
P = int((F - 1)/2)    # Padding Length

if newdata.value:
  H = 4
  W = 5
  # Random Matrix
  A = np.round(10*np.random.rand(H,W),0)
  # Laplacian Filter
  B = np.mat([[0,-1,0],[-1,4,-1],[0,-1,0]])
else:
  # Load from .mat file
  mat_dict = loadmat('ex_conv2data.mat')
  A = mat_dict['A']
  B = mat_dict['B']

  


print("A = \n" +str(A))
print("B = \n" + str(B))

# Now perform 2D convolution
C0 = convolve2d(A,B)
C = C0[P:-P,P:-P]

print("C = \n" + str(C))

A = 
[[3. 8. 0. 7. 0.]
 [4. 5. 0. 2. 1.]
 [9. 0. 5. 3. 3.]
 [4. 6. 3. 0. 9.]]
B = 
[[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]
C = 
[[  0.  24. -15.  26.  -8.]
 [ -1.   8. -12.  -3.  -1.]
 [ 28. -25.  14.   2.  -1.]
 [  1.  17.   1. -15.  33.]]
